---
- name: Configure ports of Apache
  sudo: yes
  template: src=etc/apache2/ports.conf.j2 dest=/etc/apache2/ports.conf
  notify: restart apache
  when: ansible_os_family == 'Debian'

- name: Main configuration of Apache
  sudo: yes
  template:
    src: etc/apache2/apache2.conf.j2
    dest: /etc/apache2/apache2.conf
  notify: reload apache
  when: ansible_os_family == 'Debian'

- name: Configure MPM Prefork of Apache
  sudo: yes
  template:
    src: etc/apache2/mods-available/mpm_prefork.conf.j2
    dest: /etc/apache2/mods-available/mpm_prefork.conf
  notify: reload apache
  when: ansible_os_family == 'Debian'

- name: Make sure conf available directory exists
  sudo: yes
  file:
    path: /etc/apache2/conf-available
    state: directory

- name: Configure Security of Apache
  sudo: yes
  template:
    src: etc/apache2/conf-available/security.conf.j2
    dest: /etc/apache2/conf-available/security.conf
  notify: reload apache
  when: ansible_os_family == 'Debian'

- name: Enable Apache modules
  sudo: yes
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: apache["enable_modules"]
  notify: reload apache
  when: ansible_os_family == 'Debian' and apache["enable_modules"]

- name: Disable Apache modules
  sudo: yes
  apache2_module:
    name: "{{ item }}"
    state: absent
  with_items: apache["disable_modules"]
  notify: reload apache
  when: ansible_os_family == 'Debian' and apache["disable_modules"]

- name: Ensure Apache is started and set to run on startup. "{{ apache['port'] }}"
  sudo: yes
  service: name=apache2 state=started enabled=yes
