---
- name: Configure ports of Apache
  sudo: yes
  template: src=etc/apache2/ports.conf.j2 dest=/etc/apache2/ports.conf
  notify: restart apache
  when: ansible_os_family == 'Debian'

- name: Check if conf available directory exists
  stat:
    path: /etc/apache2/conf-available
  register: conf-available

- name: Check if conf.d directory exists
  stat:
    path: /etc/apache2/conf.d
  register: confd

- name: Make sure the override conf available for Apache is present
  sudo: yes
  template:
    src: etc/apache2/conf-available/override.conf.j2
    dest: /etc/apache2/conf-available/override.conf
  notify: reload apache
  when: ansible_os_family == 'Debian' and conf-available.stat.isdir is defined and conf-available.stat.isdir == true

- name: Make sure the override conf for Apache is present
  sudo: yes
  template:
    src: etc/apache2/conf-available/override.conf.j2
    dest: /etc/apache2/conf.d/override.conf
  notify: reload apache
  when: ansible_os_family == 'Debian' and confd.stat.isdir is defined and confd.stat.isdir == true

- name: Enable override configuration in Apache
  sudo: yes
  command: a2enconf override
  notify: reload apache
  when: ansible_os_family == 'Debian' and conf-available.stat.isdir is defined and conf-available.stat.isdir == true

- name: Configure MPM Prefork of Apache
  sudo: yes
  template:
    src: etc/apache2/mods-available/mpm_prefork.conf.j2
    dest: /etc/apache2/mods-available/mpm_prefork.conf
  notify: reload apache
  when: ansible_os_family == 'Debian'

- name: Enable Apache modules
  sudo: yes
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: apache["enable_modules"]
  notify: reload apache
  when: ansible_os_family == 'Debian' and apache["enable_modules"]

- name: Disable Apache modules
  sudo: yes
  apache2_module:
    name: "{{ item }}"
    state: absent
  with_items: apache["disable_modules"]
  notify: reload apache
  when: ansible_os_family == 'Debian' and apache["disable_modules"]

- name: Ensure Apache is started and set to run on startup. "{{ apache['port'] }}"
  sudo: yes
  service: name=apache2 state=started enabled=yes
