---
- debug: var=apache verbosity=1
  tags: vars

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: post-setup.yml
