---
- name: Make sure the enabled configuration are present
  sudo: yes
  file:
    src: "../{{ apache['conf_available_path'] }}/{{ item.name }}"
    path: "{{ apache['server_root'] }}/{{ apache['conf_enabled_path'] }}/{{ item.priority }}-{{ item.name }}"
    state: link
    force: yes
  with_items:
    - { priority: z10,
        name: override.conf
      }
  notify: reload apache    
    