---
- name: Make sure the enabled configuration are present
  sudo: yes
  file:
    src: "../{{ apache['conf_available_path'] }}/{{ item.value }}.conf"
    path: "{{ apache['server_root'] }}/{{ apache['conf_enabled_path'] }}/{{ item.key }}-{{ item.value }}.conf"
    state: link
    force: yes
  with_dict: apache["extra_conf"]
  notify: reload apache    
  when: apache["extra_conf"] is defined

- name: Make sure the enabled virtualhosts are present
  sudo: yes
  file:
    src: "../{{ apache['sites_available_path'] }}/{{ item.ServerName }}.conf"
    path: "{{ apache['server_root'] }}/{{ apache['sites_enabled_path'] }}/{{ item.ServerName }}.conf"
    state: link
    force: yes
  with_items: apache["virtualhosts"]  
  notify: reload apache  
  when: apache["virtualhosts"] is defined 