---
- name: Ensure language pack is installed
  become: yes
  apt:
    name: "language-pack-en-base"

- name: Adding PPA repo for Apache2
  become: yes
  apt_repository:
    repo: 'ppa:ondrej/apache2'
  environment:
      LC_ALL: "C.UTF-8"

- name: Ensure Apache is present using apt
  become: yes
  apt:
    name: apache2
    state: present
    update_cache: yes
    cache_valid_time: 86400

- include: setup.yml

- name: Enable override configurations
  become: yes
  command: a2enconf zzz-override
  notify: reload apache
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version | version_compare('14.04', 'ge')

- name: Enable override configuration for previous Debian releases
  become: yes
  lineinfile:
    dest: "{{ apache.server_root }}/{{ apache.service }}.conf"
    line: "Include conf-enabled/*.conf"
    state: present
  notify: reload apache
  when: confd.stat.isdir is defined and confd.stat.isdir == true

- name: Enable default SSL virtualhost
  become: yes
  command: "a2ensite default-ssl"
  notify: reload apache

- name: Enable virtualhosts
  become: yes
  command: "a2ensite {{ item.directives.ServerName }}"
  with_items: "{{ apache.virtualhosts }}"
  notify: reload apache
  tags: vhost

- name: Enable Apache modules
  become: yes
  apache2_module:
    name: "{{ item }}"
    state: present
    force: yes
  with_items: "{{ apache.enable_modules }}"
  notify: reload apache

- name: Disable Apache modules
  become: yes
  apache2_module:
    name: "{{ item }}"
    state: absent
    force: yes
  with_items: "{{ apache.disable_modules }}"
  notify: reload apache
