---
- name: Check if conf available directory exists
  stat:
    path: /etc/apache2/conf.d
  register: confd
  tags: vhost

- name: Configure ports of Apache
  become: yes
  template:
    src: ports.conf.j2
    dest: "{{ apache.server_root }}/ports.conf"
  notify: restart apache

- name: Make sure configuration directories are present
  become: yes
  file:
    path: "{{ apache.server_root }}/{{ item }}"
    state: directory
  with_items:
    - sites-available
    - sites-enabled
    - conf-available
    - conf-enabled

- name: Make sure the override confs are present
  become: yes
  template:
    src: override.conf.j2
    dest: "{{ apache.server_root }}/{{ apache.conf_available_path }}/zzz-override.conf"
  notify: reload apache
  tags: apache_config

- name: Configure MPM prefork
  become: yes
  template:
    src: mpm_prefork.conf.j2
    dest: "{{ apache.server_root }}/{{ apache.mods_available_path }}/mpm_prefork.conf"
  notify: reload apache
  tags: apache_config

- name: Enable global default virtualhost
  become: yes
  lineinfile:
    dest:  "{{ apache.server_root }}/{{ apache.sites_available_path }}/000-default.conf"
    regexp: "^<VirtualHost .*>$"
    line: "<VirtualHost {% for port in apache.Listen %} *:{{ port }}{% endfor %}>"
    state: present
    backrefs: yes
  notify: reload apache
  tags: apache_config

- name: Make sure the available virtualhosts are present
  become: yes
  template:
    src: "myapp.com.conf.j2"
    dest: "{{ apache.server_root }}/{{ apache.sites_available_path }}/{{ item.directives.ServerName }}.conf"
  with_items: "{{ apache.virtualhosts }}"
  notify: reload apache
  when: item.directives.ServerName is defined
  tags: apache_vhost
