---
- name: Ensure Apache is present using apt
  sudo: yes
  apt: 
    name: apache2
    state: present

- include: setup.yml

- name: Check if conf available directory exists
  stat:
    path: /etc/apache2/conf.d
  register: confd

- name: Enable override configuration
  sudo: yes
  command: a2enconf override
  notify: reload apache
  when: confd.stat.isdir is defined and confd.stat.isdir == false

- name: Enable override configuration for previous Debian releases
  sudo: yes
  lineinfile:
    dest: "{{ apache['server_root'] }}/{{ apache['service'] }}.conf"
    line: "IncludeOptional conf-enabled/*.conf"
    state: present
  notify: reload apache  
  when: confd.stat.isdir is defined and confd.stat.isdir == true    

- name: Enable Apache modules
  sudo: yes
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: apache["enable_modules"]
  notify: reload apache
  when: apache["enable_modules"]

- name: Disable Apache modules
  sudo: yes
  apache2_module:
    name: "{{ item }}"
    state: absent
  with_items: apache["disable_modules"]
  notify: reload apache
  when: apache["disable_modules"]
