---
- name: Check if conf available directory exists
  stat:
    path: /etc/apache2/conf.d
  register: confd

- name: Configure ports of Apache
  sudo: yes
  template:
    src: etc/apache2/ports.conf.j2
    dest: "{{ apache['server_root'] }}/ports.conf"
  notify: restart apache

- name: Make sure configuration directories are present
  sudo: yes
  file:
    path: "{{ apache['server_root'] }}/{{ item }}"
    state: directory
  with_items:
    - sites-available
    - sites-enabled
    - conf-available
    - conf-enabled

- name: Make sure the override confs are present
  sudo: yes
  template:
    src: etc/apache2/conf-available/override.conf.j2
    dest: "{{ apache['server_root'] }}/{{ apache['conf_available_path'] }}/override.conf"
  notify: reload apache
  
- name: Configure MPM prefork
  sudo: yes
  template:
    src: etc/apache2/mods-available/mpm_prefork.conf.j2
    dest: "{{ apache['server_root'] }}/{{ apache['mods_available_path'] }}/mpm_prefork.conf"
  notify: reload apache

- name: Make sure the available virtualhosts are present
  sudo: yes
  template:
    src: "etc/apache2/sites-available/myapp.com.conf.j2"
    dest: "{{ apache['server_root'] }}/{{ apache['sites_available_path'] }}/{{ item.ServerName }}.conf"
  with_items: apache["virtualhosts"]
  notify: reload apache
  when: item.ServerName is defined

- name: Make sure the available SSL virtualhosts are present
  sudo: yes
  template:
    src: "etc/apache2/sites-available/myapp.com-ssl.conf.j2"
    dest: "{{ apache['server_root'] }}/{{ apache['sites_available_path'] }}/{{ item.ServerName }}-ssl.conf"
  with_items: apache["virtualhosts_ssl"]
  notify: reload apache
  when: item.ServerName is defined

- name: Make sure the SSL certificates directories are present
  sudo: yes
  file:
    dest: "/etc/ssl/{{ item.name }}"
    state: directory
  with_items: apache["certificates"]
  when: item.name is defined

- name: Make sure the SSL certificates are present
  sudo: yes
  copy:
    content: "{{ item.crt }}"
    dest: "/etc/ssl/{{ item.name }}/certificate.crt"
  with_items: apache["certificates"]
  notify: reload apache
  when: item.name is defined and item.crt is defined

- name: Make sure the SSL certificates key are present
  sudo: yes
  copy:
    content: "{{ item.key }}"
    dest: "/etc/ssl/{{ item.name }}/certificate.key"
  with_items: apache["certificates"]
  notify: reload apache
  when: item.name is defined and item.key is defined

- name: Make sure the SSL certificates intermediate are present
  sudo: yes
  copy:
    content: "{{ item.intermediate }}"
    dest: "/etc/ssl/{{ item.name }}/intermediate.crt"
  with_items: apache["certificates"]
  notify: reload apache
  when: item.name is defined and item.intermediate is defined
