---
- name: Ensure Apache is present using apt
  become: yes
  apt:
    name: apache2
    state: present
    update_cache: yes
    cache_valid_time: 86400

- include: setup.yml

- name: Enable override configurations
  become: yes
  command: a2enconf override
  notify: reload apache
  when: confd.stat.isdir is defined and confd.stat.isdir == false

- name: Enable override configuration for previous Debian releases
  become: yes
  lineinfile:
    dest: "{{ apache.server_root }}/{{ apache.service }}.conf"
    line: "Include conf-enabled/*.conf"
    state: present
  notify: reload apache
  when: confd.stat.isdir is defined and confd.stat.isdir == true

- name: Enable virtualhosts
  become: yes
  command: "a2ensite {{ item.ServerName }}"
  with_items: "{{ apache.virtualhosts }}"
  notify: reload apache
  when: item.ServerName is defined and confd.stat.isdir is defined and confd.stat.isdir == false

- name: Enable Apache modules
  become: yes
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache.enable_modules }}"
  notify: reload apache
  when: "{{ apache.enable_modules }}"

- name: Disable Apache modules
  become: yes
  apache2_module:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apache.disable_modules }}"
  notify: reload apache
  when: "{{ apache.disable_modules }}"
