---
- name: restart apache
  sudo: yes
  service: 
    name: apache2
    state: restarted
    enabled: yes

- name: reload apache
  sudo: yes
  service: 
    name: apache2
    state: reloaded
    enabled: yes
