---
- name: reload apache
  sudo: yes
  service:
    name: "{{ apache['service'] }}"
    state: reloaded
    enabled: yes

- name: restart apache
  sudo: yes
  service:
    name: "{{ apache['service'] }}"
    state: restarted
    enabled: yes

